kushapp/urls.py
from django.conf.urls import url

from . import views

#This block is needed to map our urls to views. Parameter "name" allows to use simple alias in view or on html.
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<author_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<author_id>[0-9]+)/books/$', views.books, name='books'),
	url(r'^(?P<author_id>[0-9]+)/update/$', views.update, name='update'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^kushapp/', include('kushapp.urls')),
    url(r'^admin/', admin.site.urls),
]

kushapp/models.py
from django.db import models

#These models have one-to-many dependency. 
class Author(models.Model):
    author_name = models.CharField(max_length=200)
    birth_date = models.DateTimeField('birth_date')
    
class Book(models.Model):
	#on_delete CASCADE means that all books will be deleted if parent entity will be deleted.
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    book_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date')

kushapp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from .models import Author

#Index view renders 5 authors with latest bitrh date.
def index(request):
    author_list = Author.objects.order_by('-birth_date')[:5]
    template = loader.get_template('kushapp/index.html')
    context = {
        'author_list': author_list,
    }
    return HttpResponse(template.render(context, request))

#Details view renders details about author with author_id identity.
def detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'kushapp/details.html', {'author': author})

def books(request, author_id):
    return HttpResponse("You're looking at the books of author %s." % author_id)

#Update view allows to update author with post request (new_name parameter is required).
def update(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    new_name = request.POST['new_name']
    author.author_name=new_name
    author.save()
    return render(request, 'kushapp/details.html', {'author': author})

kushapp/templates/kushapp/details.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'kushapp/style.css' %}" />
<h1>{{ author.author_name }}</h1>
{{ author.birth_date }}
<br>


<ul>
{% for book in author.book_set.all %}
    <li>{{ book.book_name }}</li>
{% endfor %}
</ul>

<br>


<h1>Update authors name</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'update' author.id %}" method="post">
{% csrf_token %}
    <input type="text" name="new_name" id="new_name" value="{{ author.author_name }}" />
    <br />
<input type="submit" value="Update" />
</form>

<br>
<br>
<a href="{% url 'index'%}">Back</a>

kushapp/templates/kushapp/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'kushapp/style.css' %}" />
{% if author_list %}
    <ul>
    {% for author in author_list %}
        <li><a href="{% url 'detail' author.id %}">{{ author.author_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No authors are available.</p>
{% endif %}